name: Release

on:
  push:
    branches:
      - main

jobs:
  tag-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: '0'

    - name: Bump version and push tag
      id: tag
      uses: anothrNick/github-tag-action@1.69.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true

    - name: Generate release changelog
      uses: heinrichreimer/action-github-changelog-generator@v2.3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        onlyLastTag: true

    - name: Create github release
      if: ${{ success() }}
      run: |
        gh release create \
          ${{ steps.tag.outputs.new_tag }} \
          --title ${{ steps.tag.outputs.new_tag }} \
          --notes-file CHANGELOG.md \
          --target main
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Skip github release
      if: ${{ failure() }}
      run: echo "Skipping github release"
